[platformio]
default_envs = esp32-h2
src_dir = main

[env:esp32-h2]
platform = espressif32
board = esp32-h2-devkitm-1
framework = espidf
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags =
  -Wall
  -Wextra
  -Werror=return-type
